spring:
  profiles:
    active: dev  # default profile
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: INFO
    com.sashel: INFO
  file:
    name: logs/app.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS}[%-5level][%logger{36}.%M]%n    ➤ Input  : %replace(%msg){'\n','\n               '}%n"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS}[%-5level][%logger{36}.%M]%n    ➤ Input  : %replace(%msg){'\n','\n               '}%n"

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

aws:
  s3:
    bucket: sashel-prod
    region: ap-south-1
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    url: https://s3.ap-south-1.amazonaws.com
  sns:
    region: ap-south-1
    topic-arn: arn:aws:sns:ap-south-1:123456789012:USER_PROFILE_TOPIC

authbridge:
  api-key: dummy123
  base-url: https://authbridge.com

interceptor:

  buyer-access-rules:

    - pattern: /api/userprofile/buyer/buyers/**
      method: GET
      roles: [ADMIN]

    - pattern: /api/userprofile/buyer/**
      method: GET
      roles: [BUYER, ADMIN]

    - pattern: /api/userprofile/buyer/**
      method: PUT
      roles: [BUYER]

    - pattern: /api/userprofile/buyer/*/status
      method: PUT
      roles: [BUYER]

    - pattern: /api/userprofile/buyer/*/addresses
      method: GET
      roles: [BUYER, SELLER, ADMIN]

    - pattern: /api/userprofile/buyer/*/addresses
      method: POST
      roles: [BUYER]

    - pattern: /api/userprofile/buyer/*/addresses/*
      method: PUT
      roles: [BUYER]

    - pattern: /api/userprofile/buyer/*/addresses/*
      method: DELETE
      roles: [BUYER]

  admin-access-rules:

    - pattern: /api/userprofile/admin/admins/**
      method: GET
      roles: [ADMIN]

    - pattern: /api/userprofile/admin/**
      method: GET
      roles: [ADMIN]

    - pattern: /api/userprofile/admin/**
      method: PUT
      roles: [ADMIN]

    - pattern: /api/userprofile/admin/*/status
      method: PUT
      roles: [ADMIN]

  seller-access-rules:

    - pattern: /api/userprofile/seller/sellers/**
      method: GET
      roles: [ADMIN]

    - pattern: /api/userprofile/seller/**
      method: GET
      roles: [ADMIN, SELLER]

    - pattern: /api/userprofile/seller/**
      method: PUT
      roles: [SELLER]

    - pattern: /api/userprofile/seller/*/status
      method: PUT
      roles: [ADMIN, SELLER]

    - pattern: /api/userprofile/seller/*/post-image
      method: POST
      roles: [SELLER]

    - pattern: /api/userprofile/seller/*/kyc-verify/pan
      method: POST
      roles: [SELLER]

    - pattern: /api/userprofile/seller/*/kyc-verify/aadhar
      method: POST
      roles: [SELLER]

    - pattern: /api/userprofile/seller/*/kyc-verify/gst
      method: POST
      roles: [SELLER]

    - pattern: /api/userprofile/seller/*/kyc-verify/bank
      method: POST
      roles: [SELLER]

    - pattern: /api/userprofile/seller/*/kyc-verify/address
      method: POST
      roles: [SELLER]

    - pattern: /api/userprofile/seller/*/brand-kyc
      method: GET
      roles: [SELLER]

    - pattern: /api/userprofile/seller/*/brand-status
      method: PUT
      roles: [SELLER]

    - pattern: /api/userprofile/seller/*/brand-logo
      method: POST
      roles: [SELLER]

    - pattern: /api/userprofile/seller/*/brand-info
      method: PUT
      roles: [SELLER]

    - pattern: /api/userprofile/seller/*/brand-reviewed
      method: PUT
      roles: [ADMIN]

    - pattern: /api/userprofile/seller/*/brand-info
      method: GET
      roles: [ADMIN, SELLER, BUYER]
