spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sashel_db
    username: springuser
    password: springpass
  jpa:
    hibernate:
      ddl-auto: update

aws:
  s3:
    accessKey: YOUR_ACCESS_KEY
    secretKey: YOUR_SECRET_KEY
    region: ap-south-1
    endpoint: https://s3.ap-south-1.amazonaws.com
    bucketName: sashel-bucket
