spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_profile_test?createDatabaseIfNotExist=true
    username: testuser
    password: testpass
  jpa:
    hibernate:
      ddl-auto: create-drop


aws:
  s3:
    accessKey: YOUR_ACCESS_KEY
    secretKey: YOUR_SECRET_KEY
    region: ap-south-1
    endpoint: https://s3.ap-south-1.amazonaws.com
    bucketName: sashel-bucket
